#!/bin/sh
#require compiletest
#require cflags
#phase init
#after init_cflags
#phase header
case $PHASE in
	init)
		dispn "Checking for pthread method..."
		PROGRAM="#include <pthread.h>

void *nothing(void *v) {
	return NULL;
}

int main () {
	pthread_t thread;
	pthread_create(&thread,NULL,nothing,NULL);
	return 0;
}"
		compile_test_wrapper "$PROGRAM" "-pthread" "" "" || \
		compile_test_wrapper "$PROGRAM" "" "" "-lpthread" || \
		{
			disp "not found, unable to continue"
			exit 1
		}
		;;
	header)
		disp "Adding \"#include <pthread.h>\" to header"
		$ECHO "#include <pthread.h>"
		;;
esac
