#!/bin/sh
#require cflags
#phase config
dispn "Reading firemake.version..."
VERSION=`cat firemake.version 2>/dev/null`
if test "$?" = "0"; then
	disp "done, \"$VERSION\""
else
	disp "not found, using \"0.0.0\""
	VERSION="0.0.0"
fi
dispn "Adding -DVERSION=\"\\\"$VERSION\\\"\" to CFLAGS..."
FM_CFLAGS="$FM_CFLAGS -DVERSION=\"\\\"$VERSION\\\"\""
disp done
