/*******************************************************
 * Psotnic framework generated by framework.sh
 * Copyright (c) 2004-2005 Grzegorz Rusin <grusin@gmail.com>
 * Created: pon sie 27 10:26:52 CEST 2007
 * 
 * WARNING! All changes made in this file will be lost!
 */

void registerAll(int (*_register)(const char *name, FUNCTION address))
{
	_register("mem_strcpy", (FUNCTION) &mem_strcpy);
	_register("ircd_strcmp", (FUNCTION) &ircd_strcmp);
	_register("ircd_strncmp", (FUNCTION) &ircd_strncmp);
	_register("itoa", (FUNCTION) &itoa);
	_register("findUser", (FUNCTION) &findUser);
	_register("sendToOwner", (FUNCTION) &sendToOwner);
	_register("sendToOwners", (FUNCTION) &sendToOwners);
	_register("getPenalty", (FUNCTION) &getPenalty);
	_register("privmsg", (FUNCTION) &privmsg);
	_register("notice", (FUNCTION) &notice);
	_register("handle", (FUNCTION) &handle);
	_register("nick", (FUNCTION) &nick);
	_register("cycle", (FUNCTION) &cycle);
	_register("server", (FUNCTION) &server);
	_register("ircIp", (FUNCTION) &ircIp);
	_register("saveUserlist", (FUNCTION) &saveUserlist);
	_register("flags2str", (FUNCTION) &flags2str);
	_register("setTopic", (FUNCTION) &setTopic);
	_register("isSticky", (FUNCTION) &isSticky);
	_register("kick4", (FUNCTION) &kick4);
	_register("kick6", (FUNCTION) &kick6);
	_register("kick", (FUNCTION) &kick);
	_register("match", (FUNCTION) &match);
	_register("srewind", (FUNCTION) &srewind);
	_register("str2words", (FUNCTION) &str2words);
	_register("findChanlist", (FUNCTION) &findChanlist);
	_register("findChannel", (FUNCTION) &findChannel);
	_register("setReason", (FUNCTION) &setReason);
	_register("addMode", (FUNCTION) &addMode);
	_register("addKick", (FUNCTION) &addKick);
	_register("flushModeQueue", (FUNCTION) &flushModeQueue);
	_register("initCustomData", (FUNCTION) &initCustomData);
	_register("knockout", (FUNCTION) &knockout);
	_register("httpget", (FUNCTION) &httpget);
	_register("findConnByHandle", (FUNCTION) &findConnByHandle);
	_register("findConnByName", (FUNCTION) &findConnByName);
	_register("set", (FUNCTION) &set);
	_register("NOW", (FUNCTION) &NOW);
	_register("penalty", (FUNCTION) &penalty);
	_register("ME", (FUNCTION) &ME);
	_register("userlist", (FUNCTION) &userlist);
	_register("net", (FUNCTION) &net);
}

