#!/bin/sh
#require makefiletop
#require prefix
#phase config
#phase makefile
#after makefile_makefiletop
case $PHASE in
	config)
		dispn "Checking for manpages for section 1..."
		MAN1=`ls man/*.1 2>/dev/null`
		disp "done"

		dispn "Checking for manpages for section 3..."
		MAN3=`ls man/*.3 2>/dev/null`
		disp "done"

		dispn "Checking for manpages for section 5..."
		MAN5=`ls man/*.5 2>/dev/null`
		disp "done"

		dispn "Checking for manpages for section 6..."
		MAN6=`ls man/*.6 2>/dev/null`
		disp "done"

		dispn "Checking for manpages for section 7..."
		MAN7=`ls man/*.7 2>/dev/null`
		disp "done"

		dispn "Checking for manpages for section 8..."
		MAN8=`ls man/*.8 2>/dev/null`
		disp "done"
		;;
	makefile)
		disp "Writing manpage installation entries..."

		$ECHO "install_man:"

		if test "$MAN1" != ""; then
			dispn "	Section 1..."
			for MAN in $MAN1; do
				$ECHO "	$INSTALL $MAN \$(MANDIR)/man1 $INSTALL_USER $INSTALL_GROUP 0644"
			done
			disp "done"
		fi

		if test "$MAN3" != ""; then
			dispn "	Section 3..."
			for MAN in $MAN3; do
				$ECHO "	$INSTALL $MAN \$(MANDIR)/man3 $INSTALL_USER $INSTALL_GROUP 0644"
			done
			disp "done"
		fi

		if test "$MAN5" != ""; then
			dispn "	Section 5..."
			for MAN in $MAN5; do
				$ECHO "	$INSTALL $MAN \$(MANDIR)/man5 $INSTALL_USER $INSTALL_GROUP 0644"
			done
			disp "done"
		fi

		if test "$MAN6" != ""; then
			dispn "	Section 6..."
			for MAN in $MAN6; do
				$ECHO "	$INSTALL $MAN \$(MANDIR)/man6 $INSTALL_USER $INSTALL_GROUP 0644"
			done
			disp "done"
		fi

		if test "$MAN7" != ""; then
			dispn "	Section 7..."
			for MAN in $MAN7; do
				$ECHO "	$INSTALL $MAN \$(MANDIR)/man7 $INSTALL_USER $INSTALL_GROUP 0644"
			done
			disp "done"
		fi

		if test "$MAN8" != ""; then
			dispn "	Section 8..."
			for MAN in $MAN8; do
				$ECHO "	$INSTALL $MAN \$(MANDIR)/man8 $INSTALL_USER $INSTALL_GROUP 0644"
			done
			disp "done"
		fi

		$ECHO
		;;
esac
