/*******************************************************
 * Psotnic framework generated by framework.sh
 * Copyright (c) 2004-2005 Grzegorz Rusin <grusin@gmail.com>
 * Created: pon sie 27 10:26:52 CEST 2007
 * 
 * WARNING! All changes made in this file will be lost!
 */

#include "framework.h"
#include "func.h"
#include "var.h"
#include "common.h"
