/*******************************************************
 * Psotnic framework generated by framework.sh
 * Copyright (c) 2004-2005 Grzegorz Rusin <grusin@gmail.com>
 * Created: wto sie 28 11:33:03 CEST 2007
 * 
 * WARNING! All changes made in this file will be lost!
 */

settings *set;
time_t *NOW;
penal *penalty;
client *ME;
ul *userlist;
inet *net;
