/*******************************************************
 * Psotnic framework generated by framework.sh
 * Copyright (c) 2004-2005 Grzegorz Rusin <grusin@gmail.com>
 * Created: Fri Apr  6 10:34:25 BST 2007
 * 
 * WARNING! All changes made in this file will be lost!
 */

extern settings *set;
extern time_t *NOW;
extern penal *penalty;
extern client *ME;
extern ul *userlist;
extern inet *net;
