/*******************************************************
 * Psotnic framework generated by framework.sh
 * Copyright (c) 2004-2005 Grzegorz Rusin <grusin@gmail.com>
 * Created: pon sie 27 09:17:16 CEST 2007
 * 
 * WARNING! All changes made in this file will be lost!
 */

extern settings *set;
extern time_t *NOW;
extern penal *penalty;
extern client *ME;
extern ul *userlist;
extern inet *net;
